/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.application.view;


import org.application.controller.dao.AmigoDao;
import org.application.model.AmigoBean;
import org.application.view.dialogAlerts.ConfirmDialog;
import org.application.view.dialogAlerts.ErrorMessageDialog;
import org.application.view.dialogAlerts.InfoMessageDialog;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

public class TelaAmigosCrud extends javax.swing.JFrame {

    private JProgressBar progressBar;

    private DefaultTableModel modelo = new DefaultTableModel();
    private AmigoDao amigoDAO = new AmigoDao();

    /**
     * Creates new form TelaPrincipal
     */
    public TelaAmigosCrud() {
        initComponents();
        initCustomComponents();
        popularTabela();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {




        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        lblDocument = new javax.swing.JLabel();
        txtDocument = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaClientes = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txtIdAmigo = new javax.swing.JTextField();
        jButtonBack = new javax.swing.JButton();
        criarAmigo = new javax.swing.JButton();
        voltarPrincipal = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuItemSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNome.setText("Nome:");

        btnSalvar.setText("Salvar");

        txtNome.setEnabled(false);
        criarAmigo.setEnabled(true);
        txtDocument.setEnabled(false);
        btnSalvar.setEnabled(false);
        jButton1.setEnabled(true);
        btnExcluir.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lblDocument.setText("Documento");

        tabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
                    tabelaClientesMouseClicked(evt);
                } catch (Exception e) {
                    throw new RuntimeException(e);
                }
            }
        });
        jScrollPane1.setViewportView(tabelaClientes);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("restore");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel1.setText("Amigos");

        jButton3.setText("Atualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtIdAmigo.setText("jTextField2");

        jButtonBack.setText("menu");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        criarAmigo.setText("Criar");
        criarAmigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarAmigoActionPerformed(evt);
            }
        });

        voltarPrincipal.setText("voltar");
        voltarPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        menuItemSair.setText("Opções");
        menuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSairActionPerformed(evt);
            }
        });

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        menuItemSair.add(jMenuItemSair);

        jMenuBar1.add(menuItemSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(268, 268, 268))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonBack)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtIdAmigo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(214, 214, 214)
                                        .addComponent(voltarPrincipal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jButton3)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(lblNome)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(32, 32, 32)
                                                .addComponent(lblDocument)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtDocument, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                    .addGap(15, 15, 15)
                                    .addComponent(criarAmigo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnExcluir)))))
                .addGap(125, 125, 125))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDocument)
                    .addComponent(txtDocument, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                        .addComponent(btnExcluir)
                        .addComponent(criarAmigo))
                    .addGap(35, 35, 35)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonBack)
                                .addComponent(voltarPrincipal)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtIdAmigo, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                    .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(ActionEvent evt) {

        jButtonBack.setEnabled(true);
        txtNome.setEnabled(false);
        criarAmigo.setEnabled(true);
        txtDocument.setEnabled(false);
        btnSalvar.setEnabled(false);
        jButton1.setEnabled(true);
        btnExcluir.setEnabled(false);

        DefaultTableModel modelo = (DefaultTableModel) tabelaClientes.getModel();
        modelo.setRowCount(0); // Limpa a tabela

        List<AmigoBean> amigos = AmigoDao.listarTodos();

        btnSalvar.setText("Salvar");


        List<AmigoBean> amigoss = AmigoDao.listarTodosOrdenadosPorNomeAsc();

        for (AmigoBean amigo : amigoss) {
            modelo.addRow(new Object[]{
                    amigo.getIdAmigo(),
                    amigo.getNome(),
                    amigo.getDocumento()
            });
        }
    }


    private void menuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemSairActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {
        ConfirmDialog confirmDialog = new ConfirmDialog("Deseja sair da aplicação?");
        confirmDialog.setVisible(true);

        if (confirmDialog.isConfirmed()) {
            System.exit(0);
        }
    }


    private void popularTabela() {
        DefaultTableModel modelo = (DefaultTableModel) tabelaClientes.getModel();
        modelo.setRowCount(0); // Limpa a tabela

        List<AmigoBean> amigos = AmigoDao.listarTodos();

        for (AmigoBean amigo : amigos) {
            modelo.addRow(new Object[]{
                    amigo.getIdAmigo(),
                    amigo.getNome(),
                    amigo.getDocumento()
            });
        }
    }


    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {
        String nome = txtNome.getText();
        String doc = txtDocument.getText();
//        String status = txtStatus.setText("Ativo");
        String status = "ATIVO";

        if (!isCamposValidos(nome, doc, status)) {
            ErrorMessageDialog errorMessageDialog = new ErrorMessageDialog("Existem campos a serem preenchidos");
            errorMessageDialog.setVisible(true);
            return;
        }


        int linhaSelecionada = tabelaClientes.getSelectedRow();

        if (linhaSelecionada >= 0) {
            Integer idAmigoSelecionado = (Integer) tabelaClientes.getValueAt(linhaSelecionada, 0);

            System.out.println("o carinha selecionado " + idAmigoSelecionado);

            // Atualizar um amigo existente com base no ID
            AmigoBean amigo = new AmigoBean(idAmigoSelecionado, nome, doc, status);
            boolean isAtualizado = AmigoDao.atualizar(amigo);

            System.out.println("status atualização " + isAtualizado);

            if (!isAtualizado) {
                modelo.setValueAt(nome, linhaSelecionada, 1);
                modelo.setValueAt(doc, linhaSelecionada, 2);
                limparCampos();
            } else {
                ErrorMessageDialog errorMessageDialog = new ErrorMessageDialog("Erro ao atualizar o amigo");
                errorMessageDialog.setVisible(true);
            }
        } else {
            // Criar um novo amigo, pois nenhum amigo está selecionado na tabela
            AmigoBean amigo = new AmigoBean(nome, doc, status);
            boolean isCadastrado = AmigoDao.inserir(amigo);

            if (isCadastrado) {
                int idAmigo = AmigoDao.getLastInsertedId();
                modelo.addRow(new Object[]{idAmigo, amigo.getNome(), amigo.getDocumento(), amigo.getStatus()});
                limparCampos();
            } else {
                InfoMessageDialog infoMessageDialog = new InfoMessageDialog("Amigo já se encontra cadastrado");
                infoMessageDialog.setVisible(true);
            }
        }
    }


    private void tabelaClientesMouseClicked(java.awt.event.MouseEvent evt) throws Exception {//GEN-FIRST:event_tabelaClientesMouseClicked

        criarAmigo.setEnabled(false);
        btnExcluir.setEnabled(true);
        int linhaSelecionada = tabelaClientes.getSelectedRow();
        Integer idAmigo = (Integer) tabelaClientes.getValueAt(linhaSelecionada, 0);
        try {
            AmigoBean amigo = AmigoDao.buscarAmigoPorId(idAmigo);
            txtNome.setText(amigo.getNome());
            txtDocument.setText(amigo.getDocumento());
        } catch (Exception err) {
            throw new Exception(err);
        }

    }//GEN-LAST:event_tabelaClientesMouseClicked

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int linhaSelecionada = tabelaClientes.getSelectedRow();

        if (linhaSelecionada >= 0) {
            ConfirmDialog confirmDialog = new ConfirmDialog("Deseja realmente excluir este Amigo?");
            confirmDialog.setVisible(true);

            if (confirmDialog.isConfirmed()) {
                Integer id = (Integer) tabelaClientes.getValueAt(linhaSelecionada, 0);
                this.amigoDAO.excluir(id);
                modelo.removeRow(linhaSelecionada);

                InfoMessageDialog infoMessageDialog = new InfoMessageDialog("Amigo excluído com sucesso");
                infoMessageDialog.setVisible(true);

                limparCampos();
            }
        } else {
            ErrorMessageDialog errorMessageDialog = new ErrorMessageDialog("Nenhum Amigo selecionado.");
            errorMessageDialog.setVisible(true);
        }



    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void atualizarTabela(List<AmigoBean> amigos) {
        DefaultTableModel modelo = (DefaultTableModel) tabelaClientes.getModel();
        modelo.setRowCount(0); // Limpa a tabela

        for (AmigoBean amigo : amigos) {
            modelo.addRow(new Object[]{
                    amigo.getIdAmigo(),
                    amigo.getNome(),
                    amigo.getDocumento()
            });
        }
    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String filtroNome = jTextField1.getText(); // Obtenha o texto do campo de filtro
        System.out.println("nome que será filtrado");

        // Crie uma instância de SwingWorker para executar a busca por nome em segundo plano
        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                // Realize a busca por nome e atualize a tabela com os resultados
                List<AmigoBean> amigosFiltrados = AmigoDao.buscarAmigosPorNome(filtroNome);

                // Atualize a tabela na UI thread
                SwingUtilities.invokeLater(() -> {
                    atualizarTabela(amigosFiltrados);
                });

                return null;
            }
        };

        worker.execute(); // Inicie a execução do SwingWorker
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        DefaultTableModel modelo = (DefaultTableModel) tabelaClientes.getModel();
        modelo.setRowCount(0); // Limpa a tabela

        List<AmigoBean> amigos = AmigoDao.listarTodosInativos();

        jButtonBack.setEnabled(true);

        btnExcluir.setEnabled(false);
        txtNome.setEnabled(false);
        txtDocument.setEnabled(false);
        criarAmigo.setEnabled(false);
        btnSalvar.setText("Restaurar");
        btnSalvar.setEnabled(true);


        jButton3.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                btnExcluir.setEnabled(true);
                txtNome.setEnabled(true);
                txtDocument.setEnabled(true);
                DefaultTableModel modelo = (DefaultTableModel) tabelaClientes.getModel();
                modelo.setRowCount(0); // Limpa a tabela

                List<AmigoBean> amigos = AmigoDao.listarTodosInativos();
            }
        });



        btnSalvar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                int selectedRow = tabelaClientes.getSelectedRow();
                if (selectedRow >= 0) {
                    int idAmigo = (int) modelo.getValueAt(selectedRow, 0);


                    for (AmigoBean amigo : amigos) {
                        if (amigo.getIdAmigo() == idAmigo) {
                            amigo.setStatus("ATIVO");
                            break;
                        }
                    }

//                    modelo.setValueAt("ATIVO", selectedRow, 3);

                }
            }
        });

        for (AmigoBean amigo : amigos) {
            modelo.addRow(new Object[]{
                    amigo.getIdAmigo(),
                    amigo.getNome(),
                    amigo.getDocumento(),
            });
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed

        PrincipalJFrame principalJFrame = new PrincipalJFrame();
        principalJFrame.setVisible(true);

    }//GEN-LAST:event_jButtonBackActionPerformed

    private void criarAmigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarAmigoActionPerformed
        txtNome.setEnabled(true);
        txtDocument.setEnabled(true);
        btnSalvar.setEnabled(true);
        jButton1.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_criarAmigoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        criarAmigo.setEnabled(true);
        btnExcluir.setEnabled(false);
        txtNome.setEnabled(false);
        txtDocument.setEnabled(false);
        btnSalvar.setEnabled(false);
        jButton1.setEnabled(false);

        DefaultTableModel modelo = (DefaultTableModel) tabelaClientes.getModel();
        modelo.setRowCount(0); // Limpa a tabela

        List<AmigoBean> amigos = AmigoDao.listarTodosOrdenadosPorNomeAsc();

        for (AmigoBean amigo : amigos) {
            modelo.addRow(new Object[]{
                    amigo.getIdAmigo(),
                    amigo.getNome(),
                    amigo.getDocumento()
            });
        }


    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAmigosCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAmigosCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAmigosCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAmigosCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAmigosCrud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton criarAmigo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblDocument;
    private javax.swing.JLabel lblNome;
    private javax.swing.JMenu menuItemSair;
    private javax.swing.JTable tabelaClientes;
    private javax.swing.JTextField txtDocument;
    private javax.swing.JTextField txtIdAmigo;
    private javax.swing.JTextField txtNome;
    private javax.swing.JButton voltarPrincipal;
    // End of variables declaration//GEN-END:variables

    private boolean isCamposValidos(String... campos) {
        for (String campo : campos) {
            if (campos == null || "".equals(campo)) {
                return false;
            }
        }
        return true;
    }

    private void initCustomComponents() {
        modelo.addColumn("Id.Amigo");
        modelo.addColumn("NOME");
        modelo.addColumn("DOCUMENTO");

        tabelaClientes.setModel(modelo);
    }

    private void limparCampos() {
        txtIdAmigo.setText("");
        txtNome.setText("");
        txtDocument.setText("");
    }
}
