/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.application.view;


import org.application.controller.dao.AmigoDao;
import org.application.controller.dao.EmprestimoDao;
import org.application.controller.dao.LivroDao;
import org.application.model.EmprestimoBean;
import org.application.model.LivroBean;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

public class TelaEmprestimo extends javax.swing.JFrame {

    private JProgressBar progressBar;

    private DefaultListModel<String> modeloListaLivros;
    private JList<String> listaLivros;

    private DefaultTableModel modelo = new DefaultTableModel();
    private EmprestimoDao emprestimoDAO = new EmprestimoDao();

    /**
     * Creates new form TelaPrincipal
     */
    public TelaEmprestimo() {
        initComponents();
        initCustomComponents();
        popularListaLivros(LivroDao.listarTodasComStatusATIVO());
        popularTabela();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jCheckBox1 = new javax.swing.JCheckBox();
        lblDescricao = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        lblAmigo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaClientes = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Devolucao = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txtIdAmigo = new javax.swing.JTextField();
        jButtonBack = new javax.swing.JButton();
        jComboBox = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuItemSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu1.setText("jMenu1");

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblDescricao.setText("Descricao");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lblAmigo.setText("Amigo");

        tabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String[]{
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        tabelaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
                    tabelaClientesMouseClicked(evt);
                } catch (Exception e) {
                    throw new RuntimeException(e);
                }
            }
        });
        jScrollPane1.setViewportView(tabelaClientes);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        lblStatus.setText("Livros");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Devolucao.setText("Devolução");
        Devolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DevolucaoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel1.setText("Emprestimos");

        jButton3.setText("Atualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtIdAmigo.setText("jTextField2");

        jButtonBack.setText("Voltar");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));

        menuItemSair.setText("Opções");
        menuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSairActionPerformed(evt);
            }
        });

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        menuItemSair.add(jMenuItemSair);

        jMenuBar1.add(menuItemSair);

        setJMenuBar(jMenuBar1);


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(70, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnSalvar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnExcluir))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(txtIdAmigo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(379, 379, 379))
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jButton3)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                                                .addComponent(jTextField1)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jButtonBack)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(Devolucao)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(lblDescricao)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addComponent(lblStatus)
                                                        .addGap(292, 292, 292)
                                                        .addComponent(lblAmigo)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(125, 125, 125))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(288, 288, 288)
                                .addComponent(jLabel1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel1)
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblDescricao)
                                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblStatus)
                                        .addComponent(lblAmigo)
                                        .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnSalvar)
                                        .addComponent(btnExcluir))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Devolucao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonBack))
                                .addGap(40, 40, 40)
                                .addComponent(txtIdAmigo, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();


        modeloListaLivros = new DefaultListModel<>();
        listaLivros = new JList<>(modeloListaLivros);
        listaLivros.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        JScrollPane scrollPane = new JScrollPane(listaLivros);
        add(scrollPane, BorderLayout.CENTER);

        // Adicione um botão para mostrar os livros selecionados
        JButton btnMostrarSelecionados = new JButton("Mostrar Selecionados");
        btnMostrarSelecionados.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Obter os livros selecionados
                List<String> livrosSelecionados = listaLivros.getSelectedValuesList();

                // Exibir os livros selecionados em uma caixa de diálogo
                String mensagem = "Livros selecionados:\n" + String.join("\n", livrosSelecionados);
                JOptionPane.showMessageDialog(TelaEmprestimo.this, mensagem);
            }
        });

        modeloListaLivros = new DefaultListModel<>();
        listaLivros = new JList<>(modeloListaLivros);

        JPanel painelBotoes = new JPanel();
        painelBotoes.add(btnMostrarSelecionados);
        add(painelBotoes, BorderLayout.SOUTH);

        // Popular a lista de livros (substitua isso com seus próprios dados)
//        popularListaLivros();


    }// </editor-fold>//GEN-END:initComponents

    private void popularListaLivros(List<LivroBean>livros) {
        // Limpar a lista antes de adicionar os novos livros
        modeloListaLivros.clear();

        // Adicionar livros da lista ao modelo
        for (LivroBean livro : livros) {
            modeloListaLivros.addElement(livro.getTitulo());  // Substitua "getTitulo()" pelo método correto para obter o título do livro
        }
    }


    private void menuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemSairActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "Deseja sair da aplicação?", "Sair",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void popularTabela() {
        DefaultTableModel modelo = (DefaultTableModel) tabelaClientes.getModel();
        modelo.setRowCount(0); // Limpa a tabela

        List<EmprestimoBean> emprestimos = EmprestimoDao.listarTodosEmprestimosDetalhados();
        System.out.println("aaaa" + emprestimos);

        for (EmprestimoBean emprestimo : emprestimos) {
            modelo.addRow(new Object[]{
                    emprestimo.getIdEmprestimo(),
                    emprestimo.getDescricao(),
                    emprestimo.getAmigo().getNome(),
                    emprestimo.getListaLivros().toArray().length
            });
        }

        List<String> nomesAmigos = AmigoDao.listarNomesAmigos();
        DefaultComboBoxModel<String> comboModel = new DefaultComboBoxModel<>(nomesAmigos.toArray(new String[0]));
        jComboBox.setModel(comboModel);
    }


    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {

        //data Emprestimo
        //data Devolução
        //descricao
        //listaLivros
        //amigo

//        String descricao = txtDescricao.getText();
//        String amigoID = txtAmigo.getText();
//        String listaLivros = txtLivros.getText();
//        String status = "ATIVO";
//        Date dataEmprestimo = new Date();
//        Date dataDevolucao = new Date();
//
//        Integer amigo = Integer.parseInt(amigoID);
//
//        List<LivroBean> livros = Integer.parseInt(editoraId);
//
//
////        String status = txtStatus.setText("Ativo");
//        String status = "ATIVO";
//
//        if (!isCamposValidos(tituto, editoraId, autorId, status)) {
//            JOptionPane.showMessageDialog(null, "Existem campos a serem preenchidos", "ATENÇÃO", JOptionPane.INFORMATION_MESSAGE);
//            return;
//        }
//
//        int linhaSelecionada = tabelaClientes.getSelectedRow();
//
//        if (linhaSelecionada >= 0) {
//            Integer idLivroSelecionado = (Integer) tabelaClientes.getValueAt(linhaSelecionada, 0);
//
//            System.out.println("o carinha selecionado " + idLivroSelecionado);
//
//            // Atualizar um amigo existente com base no ID
//            EmprestimoBean livro = new EmprestimoBean(idLivroSelecionado, tituto, status, editora, autor, null, null);
//            boolean isAtualizado = EmprestimoDao.atualizar(livro);
//
//            EmprestimoBean livroBean = EmprestimoDao.buscarLivroPorId(idLivroSelecionado);
//            System.out.println("trazeno livro selecionado" + livroBean);
//
//            System.out.println("status atualização " + isAtualizado);
//
//            if (!isAtualizado) {
//                modelo.setValueAt(livroBean.getTitulo(), linhaSelecionada, 1);
//                modelo.setValueAt(livroBean.getEditora_nome(), linhaSelecionada, 2);
//                modelo.setValueAt(livroBean.getAutor_nome(), linhaSelecionada, 3);
//                modelo.setValueAt(livroBean.getStatus(), linhaSelecionada, 4);
//                limparCampos();
//            } else {
//                JOptionPane.showMessageDialog(null, "Erro ao atualizar o livro", "ATENÇÃO", JOptionPane.INFORMATION_MESSAGE);
//            }
//        } else {
//            // Criar um novo amigo, pois nenhum amigo está selecionado na tabela
//            EmprestimoBean amigo = new EmprestimoBean(tituto, status, editora, autor);
//            boolean isCadastrado = EmprestimoDao.inserir(amigo);
//
//            if (!isCadastrado) {
//                int idLivro = EmprestimoDao.getLastInsertedId();
//                EmprestimoBean livroBean = EmprestimoDao.buscarLivroPorId(idLivro);
//                modelo.addRow(new Object[]{idLivro, livroBean.getTitulo(), livroBean.getEditora_nome(), livroBean.getAutor_nome(), livroBean.getStatus()});
//                limparCampos();
//            } else {
//                JOptionPane.showMessageDialog(null, "Livro já se encontra cadastrado", "ATENÇÃO", JOptionPane.INFORMATION_MESSAGE);
//            }
//        }

        //Amigo selecionado logico
        String amigoSelecionado = (String) jComboBox.getSelectedItem();
        if (amigoSelecionado != null) {
            // Faça algo com o amigo selecionado
            System.out.println("Amigo selecionado: " + amigoSelecionado);
        }

    }


    private void tabelaClientesMouseClicked(java.awt.event.MouseEvent evt) throws Exception {//GEN-FIRST:event_tabelaClientesMouseClicked
        int linhaSelecionada = tabelaClientes.getSelectedRow();
        Integer idAmigo = (Integer) tabelaClientes.getValueAt(linhaSelecionada, 0);
        System.out.println("o id" + idAmigo);
        try {
            EmprestimoBean livro = EmprestimoDao.buscarEmprestimoPorId(idAmigo);
            System.out.println("traz o livor" + livro);
        } catch (Exception err) {
            throw new Exception(err);
        }

    }//GEN-LAST:event_tabelaClientesMouseClicked

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int linhaSelecionada = tabelaClientes.getSelectedRow();

        if (linhaSelecionada >= 0) {
            int result = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir este Livro?", "CUIDADO",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);

            if (result == JOptionPane.YES_OPTION) {

                Integer id = (Integer) tabelaClientes.getValueAt(linhaSelecionada, 0);
                this.emprestimoDAO.excluir(id);
                modelo.removeRow(linhaSelecionada);

                JOptionPane.showMessageDialog(null, "Livro excluído com sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                limparCampos();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nenhum Livro selecionado.", "ERRO", JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void atualizarTabela(List<EmprestimoBean> emprestimos) {
        DefaultTableModel modelo = (DefaultTableModel) tabelaClientes.getModel();
        modelo.setRowCount(0); // Limpa a tabela

        for (EmprestimoBean emprestimo : emprestimos) {
            modelo.addRow(new Object[]{
                    emprestimo.getIdEmprestimo(),
                    emprestimo.getDescricao(),
                    emprestimo.getAmigo(),
                    emprestimo.getListaLivros()
            });
        }
    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String filtroNome = jTextField1.getText(); // Obtenha o texto do campo de filtro
        System.out.println("nome que será filtrado");

        // Crie uma instância de SwingWorker para executar a busca por nome em segundo plano
        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                // Realize a busca por nome e atualize a tabela com os resultados
                List<EmprestimoBean> livrosFiltrados = EmprestimoDao.buscarLivroPorNome(filtroNome);

                // Atualize a tabela na UI thread
                SwingUtilities.invokeLater(() -> {
                    atualizarTabela(livrosFiltrados);
                });

                return null;
            }
        };

        worker.execute(); // Inicie a execução do SwingWorker
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DevolucaoActionPerformed
//        btnExcluir.setEnabled(false);
//        DefaultTableModel modelo = (DefaultTableModel) tabelaClientes.getModel();
//        modelo.setRowCount(0); // Limpa a tabela
//
//        List<EmprestimoBean> livros = EmprestimoDao.listarTodosInativosComNomes();
//        System.out.println("como esses livros tão chegando" + livros);
//        System.out.println(livros);
//
//        jButtonBack.setEnabled(true);
//
//
//        btnSalvar.setText("Restaurar");
//
//        jButton3.addActionListener(new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent actionEvent) {
//                btnExcluir.setEnabled(true);
//                DefaultTableModel modelo = (DefaultTableModel) tabelaClientes.getModel();
//                modelo.setRowCount(0); // Limpa a tabela
//
//                List<EmprestimoBean> livros = EmprestimoDao.listarTodosInativosComNomes();
//
//                for (EmprestimoBean livro : livros) {
//                    modelo.addRow(new Object[]{
//                            livro.getIdLivro(),
//                            livro.getTitulo(),
//                            livro.getEditora_nome(),
//                            livro.getAutor_nome(),
//                            livro.getStatus()
//                    });
//                }
//            }
//        });
//
//
//        btnSalvar.addActionListener(new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent evt) {
//                int selectedRow = tabelaClientes.getSelectedRow();
//                if (selectedRow >= 0) {
//                    int idLivro = (int) modelo.getValueAt(selectedRow, 0);
//
//
//                    for (EmprestimoBean livro : livros) {
//                        if (livro.getIdLivro() == idLivro) {
//                            livro.setStatus("ATIVO");
//                            break;
//                        }
//                    }
//
//                    modelo.setValueAt("ATIVO", selectedRow, 4);
//                    System.out.println("aquii mudou");
//
//                }
//            }
//        });
//
//        for (EmprestimoBean livro : livros) {
//            modelo.addRow(new Object[]{
//                    livro.getIdLivro(),
//                    livro.getTitulo(),
//                    livro.getEditora_nome(),
//                    livro.getAutor_nome(),
//                    livro.getStatus()
//            });
//        }

    }//GEN-LAST:event_DevolucaoActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed


//        btnExcluir.setEnabled(true);
//        DefaultTableModel modelo = (DefaultTableModel) tabelaClientes.getModel();
//        modelo.setRowCount(0); // Limpa a tabela
//
//
//        jButtonBack.setEnabled(false);
//
//        btnSalvar.setText("Salvar");
//
//
//        List<EmprestimoBean> livros = EmprestimoDao.listarTodasComStatusATIVO();
//
//        for (EmprestimoBean livro : livros) {
//            modelo.addRow(new Object[]{
//                    livro.getIdLivro(),
//                    livro.getTitulo(),
//                    livro.getEditora_nome(),
//                    livro.getAutor_nome(),
//                    livro.getStatus()
//            });
//        }

    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {


//        DefaultTableModel modelo = (DefaultTableModel) tabelaClientes.getModel();
//        modelo.setRowCount(0); // Limpa a tabela
//
//        List<EmprestimoBean> livros = EmprestimoDao.listarTodosOrdenadosPorNomeAsc();
//
//        for (EmprestimoBean livro : livros) {
//            modelo.addRow(new Object[]{
//                    livro.getIdLivro(),
//                    livro.getTitulo(),
//                    livro.getEditora_nome(),
//                    livro.getAutor_nome(),
//                    livro.getStatus()
//            });
//        }


    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEmprestimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Devolucao;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblAmigo;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JMenu menuItemSair;
    private javax.swing.JTable tabelaClientes;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtIdAmigo;
    // End of variables declaration//GEN-END:variables

    private boolean isCamposValidos(String... campos) {
        for (String campo : campos) {
            if (campos == null || "".equals(campo)) {
                return false;
            }
        }
        return true;
    }

    private void initCustomComponents() {
        modelo.addColumn("ID");
        modelo.addColumn("DESCRICAO");
        modelo.addColumn("AMIGO");
        modelo.addColumn("QTD LIVROS EMPRESTADOS");

        tabelaClientes.setModel(modelo);
    }

    private void limparCampos() {
        txtIdAmigo.setText("");
    }
}
